### ISSUE TITLE
where is the supplement material ?

### ISSUE THREAD

**Issue by BugMaker2002** [zhaodongsun/contrast-phys#14]
Hello, I was wondering where this supplement material is?
![image](https://github.com/zhaodongsun/contrast-phys/assets/110211332/8c22d381-df10-4cc7-8367-1b99473566dc)

**Comment by ldxbxl** [comment]
> Hello, I was wondering where this supplement material is? ![image](https://private-user-images.githubusercontent.com/110211332/319890004-8c22d381-df10-4cc7-8367-1b99473566dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDEzNDAsIm5iZiI6MTcxMjMwMTA0MCwicGF0aCI6Ii8xMTAyMTEzMzIvMzE5ODkwMDA0LThjMjJkMzgxLWRmMTAtNGNjNy04MzY3LTFiOTk0NzM1NjZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwNzEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGE2OTVkYjUzMThlNDVmNDUyYTUyOWVkNGNiYzQ2NzNlY2M3ZWU3NGMwOGNjMGZmNzNkMDQzZTM5MWZjYzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dn7AZNBP0MiZ1ARHiCdeZQhBIMicSiODu0eE3cIdD_M)

Hello, I am a graduate student, and recently I have been conducting research in this field. Could you please add my contact information? My email address is 1393435924@qq.com

**Comment by zhaodongsun** [comment]
Hi, please go to https://link.springer.com/chapter/10.1007/978-3-031-19775-8_29 to download the supplement material.
![image](https://github.com/zhaodongsun/contrast-phys/assets/33407223/fc947b5b-6f78-44a6-81ee-33ed4943613f)
