### ISSUE TITLE
The MAE, MSE, and RMSE values appear to be normal, but the R-value is extremely small.

### ISSUE THREAD

**Issue by BugMaker2002** [zhaodongsun/contrast-phys#16]
The MAE, MSE, and RMSE values appear to be normal, but the R-value is extremely small.Can you tell me why?
Here's my evaluation function: I can make sure it's not wrong：
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import welch, resample
from utils_sig import hr_fft, butter_bandpass, normalize
import os


root_dir = "./results_cnn_pure/1/1"
for file in os.listdir(root_dir):
    
    if not file.endswith(".npy"):
        continue
    print(file)
    data = np.load(os.path.join(root_dir, file), allow_pickle=True)
    rppg_list = data.item().get('rppg_list')
    bvp_list = data.item().get('bvp_list')
    
    # 展平信号
    rppg = np.concatenate(rppg_list)
    # print(rppg.shape) # (1500,)
    bvp = np.concatenate(bvp_list)

    # 标准化信号
    rppg_norm = normalize(rppg)
    bvp_norm = normalize(bvp)
    

    # 计算信号长度和采样率
    signal_length = len(rppg_norm)
    fs = 30  # 假设采样率为 30Hz

    # 对标准化信号进行滤波
    rppg_filtered = butter_bandpass(rppg_norm, lowcut=0.6, highcut=4, fs=fs)
    bvp_filtered = butter_bandpass(bvp_norm, lowcut=0.6, highcut=4, fs=fs)

    # 计算预测心率和地面真值心率
    hr_rppg, rppg_psd, rppg_hr = hr_fft(rppg_filtered, fs=fs)
    hr_bvp, bvp_psd, bvp_hr = hr_fft(bvp_filtered, fs=fs)

    # 计算评估指标
    mae = np.mean(np.abs(rppg_filtered - bvp_filtered))
    mse = np.mean((rppg_filtered - bvp_filtered) ** 2)
    rmse = np.sqrt(mse)
    # print(np.corrcoef(rppg_filtered, bvp_filtered))
    r = np.corrcoef(rppg_filtered, bvp_filtered)[0, 1]

    # 绘制时域图和频谱图
    fig, (ax1, ax2) = plt.subplots(2, figsize=(20, 10))

    # 时域图
    time = np.arange(signal_length) / fs
    ax1.plot(time, rppg_filtered, label='Predicted Signal')
    ax1.plot(time, bvp_filtered, label='Ground Truth Signal')
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Amplitude')
    ax1.set_title('Predicted Signal vs Ground Truth Signal')
    ax1.legend()
    ax1.grid('on')

    # 频谱图
    ax2.plot(rppg_hr, rppg_psd, label='Predicted Signal')
    ax2.plot(bvp_hr, bvp_psd, label='Ground Truth Signal')
    ax2.set_xlabel('Heart Rate (bpm)')
    ax2.set_ylabel('Power Spectral Density')
    ax2.set_xlim([40, 200])
    ax2.set_title('Power Spectral Density of Predicted Signal vs Ground Truth Signal')
    ax2.legend()
    ax2.grid('on')

    # 显示评估指标和预测心率
    print(f"MAE: {mae:.4f}")
    print(f"MSE: {mse:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"Pearson's Correlation Coefficient (r): {r:.4f}")
    print(f"Predicted Heart Rate: {hr_rppg:.2f} bpm")
    print(f"Ground Truth Heart Rate: {hr_bvp:.2f} bpm")

    plt.show()
```

**Comment by zhaodongsun** [comment]
hi, you calculate pearson correlation by `r = np.corrcoef(rppg_filtered, bvp_filtered)[0, 1]`, which is not correct. The person correlation is between the gt_hr and pred_hr from all video clips (30s). The MAE and RMSE should also be between the gt_hr and pred_hr.

**Comment by BugMaker2002** [comment]
That is to say, if a 90s video is divided into 3 30s video clips, get 3 heart rate values hr1,hr2,hr3, then the r coefficient is correct between (rppg_hr1,rppg_hr2,rppg_hr3) and (bvp_hr1,bvp_hr2,bvp_hr3)?

**Comment by zhaodongsun** [comment]
You should gather all heart rates like (rppg_hr1,...rppg_hrN) and (bvp_hr1,...,bvp_hrN) from all video clips in the dataset and calculate Pearson correlation.

**Comment by BugMaker2002** [comment]
> You should gather all heart rates like (rppg_hr1,...rppg_hrN) and (bvp_hr1,...,bvp_hrN) from all video clips in the dataset and calculate Pearson correlation.
I noticed that you divided the original video into num_blocks video clips in the test code, so we will treat each subject, Should we average the heart rate of the num_blocks video_clip or find the corresponding heart rate after the num_blocks video_clip concatenate together?
![image](https://github.com/zhaodongsun/contrast-phys/assets/110211332/c2eb4006-ff11-422d-ab45-e38546a8474c)

**Comment by zhaodongsun** [comment]
Hi, you should not calculate metrics for each subject. You should calculate MAE, RMSE, Pearson correlation from (rppg_hr1,...rppg_hrN) and (bvp_hr1,...,bvp_hrN) in the entire test set.

**Comment by BugMaker2002** [comment]
> Hi, you should not calculate metrics for each subject. You should calculate MAE, RMSE, Pearson correlation from (rppg_hr1,...rppg_hrN) and (bvp_hr1,...,bvp_hrN) in the entire test set.

Thank you very much
