### ISSUE TITLE
Label Preprocessing

### ISSUE THREAD

**Issue by ErolCitak** [zhaodongsun/contrast-phys#19]
Hi,

What kind of pre-processing actions do we need to take for Contrast-Phys++? Any kind of normalization, etc.? 

Thanks

**Comment by zhaodongsun** [comment]
Hi, Contrast-phys+ has the same pre-processing as Contrast-Phys. You can see the pre-processing procedures in the readme file of the repo.

**Comment by ErolCitak** [comment]
Thank you for quick reply. But I was trying to understand that the range of bvp values? For example, your shared h5 file has bvp values that between around ~0 to ~12. On the other hand, I completely got the structure of h5 file, no problem about it.

**Comment by zhaodongsun** [comment]
Hi, if your bvp signal does not contain much noise, you can directly use it. The scale is not important, so you don't need to normalize it. You can also optionally filter the bvp within the heart rate range if your bvp signal is a little bit noisy.

**Comment by ErolCitak** [comment]
So clear and informative. Thanks
