### ISSUE TITLE
Different video length

### ISSUE THREAD

**Issue by ziiho08** [zhaodongsun/contrast-phys#21]
Hello,

I am attempting to train your model using the MMSE-HR and V4V datasets. However, I encountered an error, which I believe is due to the varying lengths of the videos.

I noticed the following TODO comment in the code:
```
TODO: 60 means the video length of each video is 60s. If each video's length in your dataset is another value (e.g., 30s), you should use that value.
```
Given that the videos in my dataset have different lengths, how should I handle it? Is there a recommended approach for dealing with videos of varying lengths?

Thank you for your assistance!

**Comment by zhaodongsun** [comment]
Hi, your dataset can contain videos with different lengths when using the code. You can use the average video length of your dataset. For better understanding, you can check the `H5Dataset` in `utils_data.py`.

**Comment by ziiho08** [comment]
Thank you for your response.

However, when I tried to reproduce the HR results on MMSE-HR as described in the paper, I encountered an issue where the model started producing NaN values after a few iterations. I have double-checked the experimental settings mentioned in the paper.

Could you please advise on how to resolve this issue?

**Comment by zhaodongsun** [comment]
Hi, I am unsure about the reason since I didn't encounter this issue before. Maybe you can check the data type and values in your h5 files. You may also check whether data is correctly loaded in each iteration. Since MMSE-HR dataset is 25fps, you could also check if fps is correctly set up. Did you encounter this problem on other datasets?

**Comment by ziiho08** [comment]
I found the error in the h5 files and managed to fix it! Thank you for your suggestions!

**Comment by ErolCitak** [comment]
> I found the error in the h5 files and managed to fix it! Thank you for your suggestions!

@ziiho08 Do you remember what the problem was?
