### ISSUE TITLE
Issue with signals not overlaping each other

### ISSUE THREAD

**Issue by gokdeniztrn** [zhaodongsun/contrast-phys#22]
I trained and tested contrast-phys model with UBFC dataset. Before and after butterworth filter, the signals are not overlaping when plotting on top of each other. Do you have any idea, why this is happening? One signal is ahead of the other.

![image](https://github.com/user-attachments/assets/0420dd93-b2ab-46af-a228-3ca074a999d6)

**Comment by zhaodongsun** [comment]
Hi, this is normal due to unsupervised training. Please check issue #7.

**Comment by gokdeniztrn** [comment]
Thanks a lot!
