### ISSUE TITLE
about hrv

### ISSUE THREAD

**Issue by MayYoY** [zhaodongsun/contrast-phys#3]
could you please share the code of hrv calculating?

**Comment by zhaodongsun** [comment]
Hi, I have uploaded the HRV functions to the repo. You need to use the `get_ibi` function to get inter-beat intervals (IBIs) from rPPG signals. Then use the `freq_features` function to get HRV frequency features from IBIs.

https://github.com/zhaodongsun/contrast-phys/blob/265e1700b2da5b9a276e0871ef95773df088a403/hrv.py#L1-L47

**Comment by MayYoY** [comment]
thank you very much!

**Comment by MayYoY** [comment]
sorry to bother you again, it seems `freq,power = LombScargle(np.cumsum(ibi)/1000, ibi).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` will raise an error if i directly use ibi from `get_ibi()`.
Is it right to modify it to `freq,power = LombScargle(np.cumsum(ibi[0])/1000, ibi[1]).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` ?

**Comment by zhaodongsun** [comment]
Hi, I updated the HRV code to avoid errors. You can directly input results from `get_ibi` to the `freq_features`.

**Comment by ldxbxl** [comment]
> sorry to bother you again, it seems `freq,power = LombScargle(np.cumsum(ibi)/1000, ibi).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` will raise an error if i directly use ibi from `get_ibi()`. Is it right to modify it to `freq,power = LombScargle(np.cumsum(ibi[0])/1000, ibi[1]).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` ?

I'm sorry to bother you, but I would like to know that in the test of heart rate variability, I used the predicted rppg signal of the video in the subject38 folder of the ubfc-rppg dataset as input, and the output I got was only five values, is that correct?

**Comment by ldxbxl** [comment]
> Hi, I updated the HRV code to avoid errors. You can directly input results from `get_ibi` to the `freq_features`.

If I want to get the hrv curve in a single video how do I do it?

**Comment by zhaodongsun** [comment]
> > sorry to bother you again, it seems `freq,power = LombScargle(np.cumsum(ibi)/1000, ibi).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` will raise an error if i directly use ibi from `get_ibi()`. Is it right to modify it to `freq,power = LombScargle(np.cumsum(ibi[0])/1000, ibi[1]).autopower(minimum_frequency=0.01,maximum_frequency=0.51)` ?
> 
> I'm sorry to bother you, but I would like to know that in the test of heart rate variability, I used the predicted rppg signal of the video in the subject38 folder of the ubfc-rppg dataset as input, and the output I got was only five values, is that correct?

Yes, it's correct. It should be lf_f, hf_f, lfnu, hfnu, and lf_hf_ratio. Note that lf_f is always zero since I disable the lf_f calculation.

**Comment by zhaodongsun** [comment]
> > Hi, I updated the HRV code to avoid errors. You can directly input results from `get_ibi` to the `freq_features`.
> 
> If I want to get the hrv curve in a single video how do I do it?

There is no hrv curve. I think you want to mention the inter-beat interval curve?

**Comment by ldxbxl** [comment]
> > > Hi, I updated the HRV code to avoid errors. You can directly input results from `get_ibi` to the `freq_features`.
> > 
> > 
> > If I want to get the hrv curve in a single video how do I do it?
> 
> There is no hrv curve. I think you want to mention the inter-beat interval curve?

I want to obtain this curve and use hrv related indicators such as LF/HF to calculate other indicators in the future, so a single LF/HF value does not quite meet my requirements. I think a video can obtain multiple corresponding LF/HF according to the timeline, I am not sure whether my idea is correct, please kindly help me, thank you very much.
