### ISSUE TITLE
Trained weights of Contrast-phys+

### ISSUE THREAD

**Issue by vimal-quilt** [zhaodongsun/contrast-phys#4]
Hi,
thanks for this wonderful work. i see the accuracy is much better then previous iteration of your method.
will u update this repo demo folder with latest trained weights(0%,60% & 100%) respectively.
Thanks.

**Comment by zhaodongsun** [comment]
Hi, 

Thanks for your message. I will upload the trained weights later. Contrast-Phys+ can combine labeled/unsynchronized rPPG datasets and unlabeled rPPG datasets to increase training data for better performance, while previous supervised methods can only work on well-labeled rPPG datasets. In practice, If your training data is in this weakly-supervised scenario, you could try Contrast-Phys+.

**Comment by vimal-quilt** [comment]
Thanks for the information and guidance.

**Comment by vimal-yuvabe** [comment]
Hi,
Any idea how can i get the Blood pressure/RR estimation from rppg outputs. HRV is available in your code. 
will u point me to a sample code for the above.
