### ISSUE TITLE
Blood Pressue / Respiration Rate Measurement

### ISSUE THREAD

**Issue by vimal-yuvabe** [zhaodongsun/contrast-phys#5]
Hi, 
Will u support to calculate or estimate the BP and RR from the rppg output signals.

**Comment by zhaodongsun** [comment]
Hi, 
For BP, we don't have ready-made code. You can search for some works about BP estimation from PPG signals. For RR, our HRV code can provide high frequency (HF), which is the respiration rate. There are other methods to extract respiration rates, our HRV-based method is one of the methods to extract RR from PPG. Please note that 5-min is recommended for accurate HRV parameter estimation, but a shorter length could still work.
