### ISSUE TITLE
Saliency map

### ISSUE THREAD

**Issue by ljnhahaha** [zhaodongsun/contrast-phys#6]
Hi, could you please share the code for calculating saliency maps? Thanks.

**Comment by zhaodongsun** [comment]
Hi, please refer to the files for calculating saliency maps. 
[saliency.zip](https://github.com/zhaodongsun/contrast-phys/files/14491853/saliency.zip)

**Comment by ljnhahaha** [comment]
Thank you so much.  It helps me a lot.
