### ISSUE TITLE
A bug related to contrast-phys

### ISSUE THREAD

**Issue by JasonYpro** [zhaodongsun/contrast-phys#8]
Hello, thank you very much for your kind words. I recently encountered a bug while trying to reproduce contrast-phys. I am using the UBFC-phys dataset for training and followed the preprocessing steps mentioned in the readme. However, when running train.py, I encountered the following error. Do you have any idea what could be causing the problem?

![image](https://github.com/zhaodongsun/contrast-phys/assets/79305522/0912b439-c4e9-400f-9a9c-3a4a6ee5aad9)

**Comment by zhaodongsun** [comment]
Hi, it seems your input video length is lower than the delta_t parameters. The default delta_t should be half of the video length.
