### ISSUE TITLE
Code on other datasets

### ISSUE THREAD

**Issue by BugMaker2002** [zhaodongsun/contrast-phys#9]
Could you provide code for preprocessing on other data sets? Because the UBFC-rPPG dataset is relatively simple, it is easy to handle, but it is not easy to handle when applied to other datasets such as PURE

**Comment by 408550969** [comment]
Hello, the label value of UBFC-rPPG is approximately between -1 and 1, while the PPG value I collected with CMS50E is around 60. Do you know how to obtain a label value similar to UBFC-rPPG?

**Comment by BugMaker2002** [comment]
what's CMS50E?

**Comment by 408550969** [comment]
Contec CMS50E, PPG signal acquisition device for UBFC-rPPG

**Comment by zhaodongsun** [comment]
> Could you provide code for preprocessing on other data sets? Because the UBFC-rPPG dataset is relatively simple, it is easy to handle, but it is not easy to handle when applied to other datasets such as PURE

For PURE, you can first combine the frame images into videos. Then you can follow the same pre-processing procedures by using openface to get landmarks and crop faces to save each video into `.h5` files.

**Comment by zhaodongsun** [comment]
> Hello, the label value of UBFC-rPPG is approximately between -1 and 1, while the PPG value I collected with CMS50E is around 60. Do you know how to obtain a label value similar to UBFC-rPPG?

I think the amplitude scale is not important. You can simply normalize the cPPG by z-score normalization to make zero mean and one std.

**Comment by 408550969** [comment]
> > Hello, the label value of UBFC-rPPG is approximately between -1 and 1, while the PPG value I collected with CMS50E is around 60. Do you know how to obtain a label value similar to UBFC-rPPG?
> 
> I think the amplitude scale is not important. You can simply normalize the cPPG by z-score normalization to make zero mean and one std.

Thanks！
